{% set name = "pytest-shell" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-shell-{{ version }}.tar.gz
  sha256: f89a26a3b36b114a9148857101cda0744422fcb528de08311c7e2cdd8892e885

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - pytest
    - python >=3.6

test:
  imports:
    - pytest_shell
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hg.sr.ht/~danmur/pytest-shell
  summary: A pytest plugin for testing shell scripts and line-based processes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
