{% set name = "pytest-shell" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-shell-{{ version }}.tar.gz
  sha256: 1f67c3b84b3e8a08d3a39f14cbcc2cfd8963d963d218ca37bbd743083d4ee764

build:
  number: 0
  noarch: python
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - pytest
    - python >=3.6
    - where >=1.0.2,<2.0.0

test:
  imports:
    - pytest_shell
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hg.sr.ht/~danmur/pytest-shell
  summary: A pytest plugin for testing shell scripts and line-based processes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
