{% set name = "pytest-shell" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-shell-{{ version }}.tar.gz
  sha256: 7e30cf518a5271328f25eaa9013e1639607f169d7396a4b85204a8b34dacbab1

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - pytest
    - python >=3.6
    - where >=1.0.2,<2.0.0

test:
  imports:
    - pytest_shell
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hg.sr.ht/~danmur/pytest-shell
  summary: A pytest plugin for testing shell scripts and line-based processes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
